namespace zivillian.ldap
{
    public enum ResultCode
    {
        /* ENUMERATED {
         *           success                      (0),
         *           operationsError              (1),
         *           protocolError                (2),
         *           timeLimitExceeded            (3),
         *           sizeLimitExceeded            (4),
         *           compareFalse                 (5),
         *           compareTrue                  (6),
         *           authMethodNotSupported       (7),
         *           strongerAuthRequired         (8),
         *  -- 9 reserved --
         *           referral                     (10),
         *           adminLimitExceeded           (11),
         *           unavailableCriticalExtension (12),
         *           confidentialityRequired      (13),
         *           saslBindInProgress           (14),
         *           noSuchAttribute              (16),
         *           undefinedAttributeType       (17),
         *           inappropriateMatching        (18),
         *           constraintViolation          (19),
         *           attributeOrValueExists       (20),
         *           invalidAttributeSyntax       (21),
         *  -- 22-31 unused --
         *           noSuchObject                 (32),
         *           aliasProblem                 (33),
         *           invalidDNSyntax              (34),
         *  -- 35 reserved for undefined isLeaf --
         *           aliasDereferencingProblem    (36),
         *  -- 37-47 unused --
         *           inappropriateAuthentication  (48),
         *           invalidCredentials           (49),
         *           insufficientAccessRights     (50),
         *           busy                         (51),
         *           unavailable                  (52),
         *           unwillingToPerform           (53),
         *           loopDetect                   (54),
         *  -- 55-63 unused --
         *           namingViolation              (64),
         *           objectClassViolation         (65),
         *           notAllowedOnNonLeaf          (66),
         *           notAllowedOnRDN              (67),
         *           entryAlreadyExists           (68),
         *           objectClassModsProhibited    (69),
         *  -- 70 reserved for CLDAP --
         *           affectsMultipleDSAs          (71),
         *  -- 72-79 unused --
         *           other                        (80),
         *           ...  },
         */
        Success                      = 0,
        OperationsError              = 1,
        ProtocolError                = 2,
        TimeLimitExceeded            = 3,
        SizeLimitExceeded            = 4,
        CompareFalse                 = 5,
        CompareTrue                  = 6,
        AuthMethodNotSupported       = 7,
        StrongerAuthRequired         = 8,
        Referral                     = 10,
        AdminLimitExceeded           = 11,
        UnavailableCriticalExtension = 12,
        ConfidentialityRequired      = 13,
        SaslBindInProgress           = 14,
        NoSuchAttribute              = 16,
        UndefinedAttributeType       = 17,
        InappropriateMatching        = 18,
        ConstraintViolation          = 19,
        AttributeOrValueExists       = 20,
        InvalidAttributeSyntax       = 21,
        NoSuchObject                 = 32,
        AliasProblem                 = 33,
        InvalidDnSyntax              = 34,
        AliasDereferencingProblem    = 36,
        InappropriateAuthentication  = 48,
        InvalidCredentials           = 49,
        InsufficientAccessRights     = 50,
        Busy                         = 51,
        Unavailable                  = 52,
        UnwillingToPerform           = 53,
        LoopDetect                   = 54,
        NamingViolation              = 64,
        ObjectClassViolation         = 65,
        NotAllowedOnNonLeaf          = 66,
        NotAllowedOnRdn              = 67,
        EntryAlreadyExists           = 68,
        ObjectClassModsProhibited    = 69,
        AffectsMultipleDsAs          = 71,
        Other                        = 80
    }
}